server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.115.148:3306/powerrangers_event_management_system?serverTimezone=GMT%2b10
    username: root
    password: RedBlack1129Hash
    hikari:
      max-lifetime: 30000

  freemarker:
    enabled: true
    template-loader-path: classpath:/templates/
    suffix: .ftl
    content-type: text/html
    check-template-location: true
    cache: false
    charset: UTF-8
    allow-request-override: false
    allow-session-override: false
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true

  web:
    swaggerStartUpUrl: http://localhost:8081/swagger-ui/index.html

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 1.15.115.148
    port: 6379
    timeout: 6000
    jedis:
      pool:
        min-idle: 0
        max-idle: 10
        max-wait: -1
        max-active: 200
    password: RedBlack1129Hash

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

JWT:
  expiration: 172800000

EmailApi:
  url: http://api.sendcloud.net/apiv2/mail/send
  apiUser: sc_bjklvn_test_dBTXGm
  apiKey: 826a23a47afc7cc97e721a03b35bce6b

DefaultImage:
  eventImage: https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png
  userAvatar: https://joeschmoe.io/api/v1/random

