server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.115.148:3306/powerrangers_event_management_system?serverTimezone=GMT%2b10
    username: root
    password: 123456
    #data: classpath:powerrangers_event_management_system.sql
    #initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
