export const categoryList = [
  {
    id: 1,
    value: 'on-line',
    label: '🚩 on-line',
  },
  {
    id: 2,
    value: 'offline',
    label: '🚩 offline',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'mHealthUX: How To Design a Mobile Health App ',
    serviceTime: '2022-08-28 14:00:00',
    deliveryFee: 3.44,
    category: 'place',
    cuisine: 'american',
    rating: 5,
    price: 250,
    coverSrc: '/img/slide1.png',
  },
  {
    id: 2,
    title: 'Introductory Workshop to Chinese Music',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 4.94,
    category: 'place',
    cuisine: 'italian',
    rating: 4,
    price: 100,
    coverSrc: '/img/slide2.png',
  },
  {
    id: 3,
    title: 'Anzac Memorial Tour and Lunch',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 4.94,
    category: 'place',
    cuisine: 'chinese',
    rating: 3,
    price: 200,
    coverSrc: '/img/slide3.png',
  },
  {
    id: 4,
    title: 'Drum Jam',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 2.14,
    category: 'place',
    cuisine: 'american',
    rating: 1,
    price: 180,
    coverSrc: '/img/slide4.png',
  },
  {
    id: 5,
    title: 'Disability Connection Expo 2022',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 6.79,
    category: 'place',
    cuisine: 'italian',
    rating: 5,
    price: 200,
    coverSrc: '/img/slide5.png',
  },
  {
    id: 6,
    title: 'Bondi Aboriginal Walking Tour with Walangari Karntawarra',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 2.87,
    category: 'place',
    cuisine: 'chinese',
    rating: 5,
    price: 300,
    coverSrc: '/img/slide6.png',
  },
  {
    id: 7,
    title: 'Ecommerce Marketing How we Built $50 MILLION Ecommerce business in 1 year',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 8.5,
    category: 'dish',
    cuisine: 'american',
    rating: 2,
    price: 220,
    coverSrc: '/img/slide7.png',
  },
  {
    id: 8,
    title: 'Back to the Disco',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 1.8,
    category: 'dish',
    cuisine: 'italian',
    rating: 1,
    price: 190,
    coverSrc: '/img/slide8.png',
  },
  {
    id: 9,
    title: 'Street Art Melbourne : Outdoor Escape Game',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 3.33,
    category: 'dish',
    cuisine: 'chinese',
    rating: 4,
    price: 275,
    coverSrc: '/img/slide9.png',
  },
  {
    id: 10,
    title: 'ONLINE DANCE PARTY',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 1.9,
    category: 'dish',
    cuisine: 'american',
    rating: 2,
    price: 435,
    coverSrc: '/img/slide10.png',
  },
  {
    id: 11,
    title: 'ONLINE DANCE PARTY',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 4.1,
    category: 'dish',
    cuisine: 'italian',
    rating: 3,
    price: 330,
    coverSrc: '/img/slide11.jpg',
  },
  {
    id: 12,
    title: 'ONLINE DANCE PARTY',
    serviceTime: '2022-09-15 22:00:00',
    deliveryFee: 1.5,
    category: 'dish',
    cuisine: 'chinese',
    rating: 2,
    price: 410,
    coverSrc: '/img/slide1.png',
  },
];